dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N004
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N005
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N006
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N008
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N009
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N010
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N011
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N012
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N013
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N014
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N015
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N016
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N017
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N018
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N019
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N020
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N021
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N022
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N023
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N024
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N025
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N026
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N027
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N028
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N029
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N030
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N031
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N032
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N033
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N034
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N035
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N036
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N037
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N039
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N043
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N044
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N045
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N046
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N047
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N048
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N050
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N051
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N053
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N054
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N055
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N056
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N057
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N058
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N059
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N061
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N066
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N068
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N074
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N075
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N076
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N077
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N078
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N079
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N080
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N081
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N082
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N083
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N084
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N085
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N086
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N087
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N088
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N089
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N091
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N093
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N105
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N106
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N107
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N108
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N110
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N112
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N113
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N116
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N119
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N121
dcm2nii   -b I:\ProfSoftware\gretna\MRIcroN\dcm2niigui.ini  F:\Data\HuaXi_ZhangJunRan_MDD\T1\NC\N124